language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

cache:
    directories:
        - $HOME/.composer/cache

branches:
    only:
        - master

before_script:
    - composer install

script:
    - bin/phpspec run -fpretty
    - bin/php-cs-fixer --diff --dry-run -v fix
